# Generated by Django 5.2.6 on 2025-10-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('Homme', 'homme'), ('Femme', 'femme')], max_length=10)),
                ('contact', models.CharField(max_length=15)),
                ('deja_baptiser', models.BooleanField(default=False)),
                ('eglise', models.CharField(max_length=100)),
                ('servir_avec_nous', models.BooleanField(default=False)),
                ('besoin_de_priere', models.BooleanField(default=False)),
                ('requete_priere', models.TextField(blank=True, null=True)),
                ('suggestion_amelioration', models.TextField(blank=True, null=True)),
                ('categorie_membres', models.CharField(choices=[('Membre', 'membre'), ('Visiteur', 'visiteur'), ('Ame_Evangelisee', 'ame_evangelisee'), ('Serviteur', 'serviteur')], max_length=50)),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('avenue', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.IntegerField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('create', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
