# Generated by Django 5.2.6 on 2025-10-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infomgj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministeres',
            name='adresse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ministeres',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ministeres',
            name='logos',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='ministeres',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ministeres',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
